name: sixvalley_vendor_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^8.0.0
  provider: ^6.1.2

  dio: ^5.7.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_switch: ^0.3.2
  fl_chart: ^0.69.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^5.2.0
  autocomplete_textfield: ^2.0.1
  dotted_border: ^2.1.0
  flutter_html: ^3.0.0-alpha.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.0.15
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.0.9
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.8
  barcode_widget: ^2.0.2
  file_picker: 8.1.2
  url_launcher: ^6.1.5
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  flutter_speed_dial: ^7.0.0
  image: ^3.0.2

#    git:
#      url: https://github.com/itsAyyazdev/flutter_barcode_scanner.git
#  flutter_pos_printer_platform: ^1.0.9
  esc_pos_utils: ^1.1.0
  flutter_slidable: ^3.1.1
  readmore: ^2.2.0
  flutter_html_table: ^3.0.0-alpha.3
  google_maps_flutter: ^2.2.2
  syncfusion_flutter_datepicker: ^27.1.51
  textfield_tags: ^2.0.2
  http: ^1.2.2
  path: ^1.8.2
  typed_data: ^1.3.1
  http_parser: ^4.0.2
  animated_floating_buttons: ^0.0.2
  barcode_scan2: ^4.3.3
  













dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/ubuntu/Ubuntu-Bold.ttf
          weight: 600